# Firefox Cookie Service for EasyPanel Deployment
version: '3.8'

services:
  firefox-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firefox-cookie-service
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DISPLAY=:99
      - FIREFOX_PROFILE_PATH=/app/firefox-profile
      - COOKIES_PATH=/app/cookies
      - VNC_PASSWORD=firefox123
      - ALLOWED_ORIGINS=http://localhost:5000,https://taivideonhanh.vn
      
    # Ports
    ports:
      - "3000:3000"  # API port
      - "6080:6080"  # noVNC web interface
      - "5900:5900"  # VNC port (optional, for direct VNC clients)
    
    # Volumes for persistent storage
    volumes:
      - firefox-profile:/app/firefox-profile
      - firefox-cookies:/app/cookies
      - firefox-logs:/app/logs
      
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security
    security_opt:
      - seccomp:unconfined
    
    # Shared memory size (important for Firefox)
    shm_size: 2gb
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    # Networks
    networks:
      - firefox-network
      - taivideonhanh-network  # Connect to main app network

# Volumes for persistent data
volumes:
  firefox-profile:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/firefox-profile
      
  firefox-cookies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/cookies
      
  firefox-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/logs

# Networks
networks:
  firefox-network:
    driver: bridge
    
  taivideonhanh-network:
    external: true  # Connect to existing app network
